server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

